### ISSUE TITLE
micro-bit-hello-world compile error

### ISSUE THREAD

**Issue by FBSeletronica** [lancaster-university/microbit-samples#30]
Hello,

I'm trying to compile micro-bit-hello-world example in mbed compiler and I got this error:

Error: '.syntax divided' arm assembly not supported in "microbit/microbit-dal/nRF51822/nrf51-sdk/source/nordic_sdk/components/drivers_nrf/delay/nrf_delay.h", Line: 266, Col: 6

Someone could help me?

I imported the example from this page: https://os.mbed.com/teams/microbit/
![Captura de tela de 2019-09-28 17-41-58](https://user-images.githubusercontent.com/4184762/65822283-cb08fd80-e217-11e9-8a25-2974da620d8a.png)

**Comment by jamesadevine** [comment]
As that particular version of the DAL is pretty old, I would suspect that the mbed online compiler has been changed in someway to result in this output. Unfortunately, we have no control over the mbed online compiler and it may take some time to resolve, have you considered installing the toolchains locally?

@jaustin The ARMCC 6 compiler is not accounting for syntax divided in inline assembly (which is perfectly valid).

**Comment by FBSeletronica** [comment]
@jamesadevine thanks for the feedback. 

Two weeks ago I compiled this same code and had no problems. I installed yotta and managed to compile offline but now I'm preparing a workshop with micro:bit and mbed and it would be better to use the online compiler.

**Comment by madchutney** [comment]
Hi @FBSeletronica ,

Apologies for the inconvenience, the Mbed Online Compiler has now been fixed. This was caused by the online compiler incorrectly selecting the Arm C6 toolchain for the micro:bit library after the last release.

**Comment by FBSeletronica** [comment]
@madchutney thank you very much!

**Comment by jamesadevine** [comment]
Wow thanks for the quick fix @madchutney :smile:
